### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement fireducks

### ISSUE THREAD

**Issue by Shigeyuki-Matsunami** [fireducks-dev/fireducks#1]
下記のサイトから、pip installを試しましたが、下記のエラーがでてinstallが進みません。
https://fireducks-dev.github.io/ja/docs/get-started/get-started/

OS: Win 11
IDE：anaconda navigator 2.3.2

(base) C:\Users\smatsu>pip install fireducks
ERROR: Could not find a version that satisfies the requirement fireducks (from versions: none)
ERROR: No matching distribution found for fireducks

**Comment by k-ishizaka** [comment]
ご報告ありがとうございます．現在Windows版は用意していません．リクエストが多い様でしたら考えたいと思います．

**Comment by Shigeyuki-Matsunami** [comment]
@k-ishizaka 
windows版がないことで、承知いたしました。
pythonの高速ライブラリとして期待しておりますので、前向きにご検討をいただければ多くの方にも利用されるかと思います。
