### ISSUE TITLE
Can't conda install fireducks

### ISSUE THREAD

**Issue by EED85** [fireducks-dev/fireducks#12]
Hi everyone,

which channel shall i use? It does not seem to be present in conda-forge.

```
$ conda install -y fireducks
Channels:
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - fireducks
```

Eric

**Comment by xxsl** [comment]
Conda is not the official source yet. Please use pypi (pip) instead.

**Comment by qsourav** [comment]
@EED85, thank you very much for your query and interest in using FireDucks!

Its not yet registered on the conda package environment. We will work on it. 
For the time being, would you like to try using "pip install"? (as suggested by @xxsl)

**Comment by EED85** [comment]
Hi @qsourav ,

thanks for the hint. As we are locking all our environments with conda, we can use this package in production, only if it is available in conda.

I am looking forward to the registration!

Eric

**Comment by EED85** [comment]
Hi,

do you have any update here?
