### ISSUE TITLE
pd.read_pickle error

### ISSUE THREAD

**Issue by weidinger-c** [fireducks-dev/fireducks#16]
When using the newest version 0.12.2, I get an error when trying to load a pandas df from pickle:

`tile = pd.read_pickle("debug.tile")`

```
No module named 'numpy._core.numeric'
ModuleNotFoundError: No module named 'numpy._core.numeric'
```

UPDATE:
it seems that the installation of fireducks did something with my numpy installation

```
pip install fireducks
Defaulting to user installation because normal site-packages is not writeable
Collecting fireducks
  Downloading fireducks-0.12.2-cp310-cp310-manylinux_2_28_x86_64.whl (6.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 MB 34.9 MB/s eta 0:00:00
Collecting numpy<2.0
  Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 36.2 MB/s eta 0:00:00
Collecting firefw==0.12.2
  Downloading firefw-0.12.2-py3-none-any.whl (12 kB)
Requirement already satisfied: pandas<2.3.0,>=1.5.3 in /home/vscode/.local/lib/python3.10/site-packages (from fireducks) (2.2.2)
Collecting pyarrow<16.2,>=16.1
  Downloading pyarrow-16.1.0-cp310-cp310-manylinux_2_28_x86_64.whl (40.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 MB 20.2 MB/s eta 0:00:00
Collecting numba
  Downloading numba-0.60.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 33.8 MB/s eta 0:00:00
Requirement already satisfied: pytz>=2020.1 in /home/vscode/.local/lib/python3.10/site-packages (from pandas<2.3.0,>=1.5.3->fireducks) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/vscode/.local/lib/python3.10/site-packages (from pandas<2.3.0,>=1.5.3->fireducks) (2024.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/vscode/.local/lib/python3.10/site-packages (from pandas<2.3.0,>=1.5.3->fireducks) (2.9.0.post0)
Collecting llvmlite<0.44,>=0.43.0dev0
  Downloading llvmlite-0.43.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.9/43.9 MB 17.5 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in /home/vscode/.local/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas<2.3.0,>=1.5.3->fireducks) (1.16.0)
Installing collected packages: numpy, llvmlite, firefw, pyarrow, numba, fireducks
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.0
    Uninstalling numpy-2.0.0:
      Successfully uninstalled numpy-2.0.0
Successfully installed fireducks-0.12.2 firefw-0.12.2 llvmlite-0.43.0 numba-0.60.0 numpy-1.26.4 pyarrow-16.1.0
```

**Comment by qsourav** [comment]
Hello @weidinger-c,

Hope you are doing well. Glad to hear from you!

Due to some issues with numpy 2.0.0, we have set numpy dependency as (< 2.0.0) for FireDucks. 

I can see the message saying "Uninstalling numpy-2.0.0:", 
but can you please confirm if you observed the following message as well? 
If not, then maybe the installation is not successful. Kindly try it once again.
> Successfully installed fireducks-0.12.2 firefw-0.12.2 llvmlite-0.43.0 numba-0.60.0 numpy-1.26.4 pandas-2.2.2 ....

When I tried to reproduce your situation, it works at my end:
```
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fireducks.pandas as pd
>>> pd.__version__
'0.12.2'
>>> import numpy as np
>>> np.__version__
'1.26.4'
>>> df = pd.DataFrame({"a": [1,2,3,4]})
>>> pd.to_pickle(df, "tmp.pkl")
>>> pd.read_pickle("tmp.pkl")
   a
0  1
1  2
2  3
3  4
```

**Comment by weidinger-c** [comment]
Sorry, I update the output above. Yes it does say that line.

**Comment by qsourav** [comment]
Hmmm… Can you also provide some more details for us to reproduce your issue: version of python, pandas, numpy, numba and fireducks?

Also, if you are not dealing with array/column of type float16, then probably you may like to upgrade numpy (as pip install numpy==2.0.0) and use latest version of FireDucks (0.12.2). We are working on resolving numpy dependency and probably will include it in next release.

**Comment by qsourav** [comment]
Also, if you have saved (to_pickle) the data previously using numpy 2.0.0 and loading the same data (read_pickle) using numpy 1.26.4, this error might occur. I haven’t confirmed it yet though.

**Comment by qsourav** [comment]
@weidinger-c ,

Hope you are doing well. 

This is to inform you that with today's release (0.12.3), we have fixed the following two issues reported last time:
- numpy version dependency issue
- aggregation (max, mion etc.) issue on uint16 typed columns. 

We would greatly appreciate it if you could kindly confirm the situation with the latest version of FireDucks.

**Comment by weidinger-c** [comment]
Hi, I just tested the latest release and there are no errors on my side. Performance-wise unfortunately the my lib got way worse than with normal pandas. I will have to see at which code parts the performance gets lost.

**Comment by qsourav** [comment]
Be alert, as the performance might deteriorate due to internal fallback to pandas. 
You may like to check here to avoid fallback: https://fireducks-dev.github.io/docs/user-guide/tips/#avoid-fallback

If you execute your program with the environment variable set as `FIREDUCKS_FLAGS="--trace=3"`,
it will produce a `trace.json` file containing several traces related to your program's performance. 

If you find that your program's performance is not meeting your expectations, you may like to share the trace.json (it doesn't contain any confidential information related to your data). We will look into the same and may suggest alternative measures.
Also, we may like to support the feature if it seems important for you by avoiding fallback.

**Comment by weidinger-c** [comment]
I tried you env flags, and I get many fallback warnings. Would it be possible to provide you the json file and other insights per email?

**Comment by qsourav** [comment]
> Would it be possible to provide you the json file and other insights per email?

Yes, please share the trace.json file over an email: contact@fireducks.jp.nec.com
We will be happy to support you.
