### ISSUE TITLE
Enabling GPU as backend

### ISSUE THREAD

**Issue by weidinger-c** [fireducks-dev/fireducks#17]
Hi,

I read that one can switch the backend from CPU to GPU by env variables. Can you describe how to do this?

(Web Page:
"_FireDucks allows the backend to be changed, for example, a backend tuned for multi-core, a backend using accelerators such as GPUs, etc., to match the target environment, thereby increasing speed. The backend can be changed by environment variables, allowing the user to switch backends without changing the user program at all._")

**Comment by qsourav** [comment]
@weidinger-c ,

Thank you for your query.

The free version of FireDucks actually doesn't include the support for the GPU backend. 

We appreciate your kind understanding.

**Comment by jmakov** [comment]
Do [the benchmarks](https://fireducks-dev.github.io/docs/benchmarks/) include Fireducks running on a GPU? Also, how does one get access to the GPU backend for evaluation?

**Comment by qsourav** [comment]
Hi @jmakov,

Thnak you for your query.

The benchmarks results presented in our website is from the CPU version of FireDucks. 
The GPU version is still under development and we will notify you once it is ready, if you are interested in evaluating the same.

Thank and Regards,
Sourav Saha
