### ISSUE TITLE
Question: how to reproduce tpc-h benchmarks?

### ISSUE THREAD

**Issue by MarcoGorelli** [fireducks-dev/fireducks#30]
Taking the conversation started in https://github.com/fireducks-dev/fireducks/issues/29 forwards

From reading the Fireducks website, I was under the impression that the way to accelerate pandas code was to run it with `python -m fireducks.pandas`. However, from trying to do that in https://www.kaggle.com/code/qsourav91/tpc-h-polars-vs-duckdb-vs-fireducks-pandas, I'm seeing results ~10 slower than Polars

In [this comment](https://github.com/fireducks-dev/fireducks/issues/29#issuecomment-2497137039) it's suggested to call `_evaluate`, which I don't understand, because:
- it looks like it's a private method?
- the website says "Accelerate pandas without any manual code changes", why do I need to add an extra `_evaluate`?

Sorry if I'm being slow here, just trying to understand what's going on

**Comment by MarcoGorelli** [comment]
yup, thanks! will check the differences between the folders then

**Comment by MarcoGorelli** [comment]
> The IRs are efficiently optimized and executed when a reduction or print related methods, like: print, repr, to_csv, plot, sum, max, min, etc. is triggered.

just out of interest, are the results cached? so, if someone calls `print` twice, does that risk triggering an whole expensive pipeline twice?

**Comment by qsourav** [comment]
It depends on how the program is written:

For example,
```
df = pd.read_csv(...).groupby(...).sum()
print(df)
print(df)
```
The "df" will be cached and will not be computed two times (sinece already evaluated).

But, when written as follows, it will get evaluated two times:
```
print(pd.read_csv(...).groupby(...).sum())
print(pd.read_csv(...).groupby(...).sum())
```
