### ISSUE TITLE
[BUG] `.to_csv` method crash when DataFrame contains datetime64 with timezone

### ISSUE THREAD

**Issue by xxsl** [fireducks-dev/fireducks#5]
It seems that `to_csv` fails when DataFrame contains any datetime64 dtype **with a timezone**.

For example:
```python
import fireducks.pandas as pd
sample_data = [['2024-02-16 10:30:00']]
df = pd.DataFrame(sample_data, columns = ["time_str"])
df["time_type"] = pd.to_datetime(df["time_str"], utc=True)

print(df) # <--- ok

df.to_csv("temp1.csv") # <--- crash
```
![2024-02-16_18-07](https://github.com/fireducks-dev/fireducks/assets/7067381/a6e17b1a-9841-48a1-b247-a083c904c9cb)

You can see that only `to_csv` method crashed, other operation (aware that I did not check all of the dataframe methods) seems to be fine. 

![2024-02-16_18-15](https://github.com/fireducks-dev/fireducks/assets/7067381/5dddf3b9-54e1-4786-bf1c-73df9d5d73c5)

On the other hand, original Pandas can handle this well:

![2024-02-16_18-31](https://github.com/fireducks-dev/fireducks/assets/7067381/3a7a3bdb-57d6-420d-bb1a-5af1ef1c0a71)

So I guess there might be something wrong handling datetime64 with timezone inside `to_csv` method of FireDucks dataframe.
Please check that, thanks.

Also, any other situation which leads to a datetime64 type with timezone generated will crash at `to_csv` as well, like:

```python
import fireducks.pandas as pd
sample_data = [['2024-02-16 8:46:00+9:00']] # <--- datetime string in ISO 8601 format with a timezone offset
df = pd.DataFrame(sample_data, columns = ["time_str"])
df["time_type"] = pd.to_datetime(df["time_str"]) # <--- note that no utc parameter set here
df.to_csv("temp2.csv") # <--- crash
```

![2024-02-16_18-03](https://github.com/fireducks-dev/fireducks/assets/7067381/de30f71e-e3f3-4f19-9125-723a9ee75b98)

- FireDucks version: 0.10.0
- OS: Ubuntu 22.04.3 LTS (GNU/Linux 6.1.0-17-amd64 x86_64)
- Python3 version: Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux

**Comment by xxsl** [comment]
I can still confirm this issue when using FireDucks version: 0.10.2:
![2024-02-29_16-35](https://github.com/fireducks-dev/fireducks/assets/7067381/4b753d41-0644-4026-904d-7aebf55c7766)

**Comment by k-ishizaka** [comment]
Thank you for reporting problems. I was able to reproduce the first problem on the system which does not have `/usr/share/zoneinfo`. On the other hand I can successfully run the same program on the system with it.

Since this problem should come from the external library which fireducks is using internally, I am not sure that we can fix this problem soon.  As a workaround, installing tzdata package would fix the problem.

**Comment by xxsl** [comment]
Hi @k-ishizaka ,

Thanks for your help and explanations.
After installed `tzdata`, the problem solved.

![2024-03-07_17-37](https://github.com/fireducks-dev/fireducks/assets/7067381/39f70f86-2c67-495b-8ada-042046fd643d)

Maybe because my environment is based on docker container (nvidia/cuda:11.8.0-runtime-ubuntu22.04), it's lack of `tzdata` package by default.

After doing

```bash
apt-get install tzdata
```

I got this fixed.

Appreciate for your help!
