### ISSUE TITLE
[BUG] `.read_csv` error when meets csv rows missing the last field element

### ISSUE THREAD

**Issue by xxsl** [fireducks-dev/fireducks#7]
Sometimes we could have csv files not that strictly formatted,

For example:

```csv
student_id,score
1001,A
1002,A
1003
1004,B
```

Pandas can handle this case very well:

![2024-02-24_22-41](https://github.com/fireducks-dev/fireducks/assets/7067381/133408d8-e4de-47a4-a005-70f5dc3ca1ae)

But FireDucks raises parse error on this kind of cases:

![2024-02-24_22-43](https://github.com/fireducks-dev/fireducks/assets/7067381/2d8508bf-854c-4b3c-8f74-5bb78de22daa)

By referencing [RFC 4180](https://www.ietf.org/rfc/rfc4180.txt), we can see it requires `Each line should contain the same number of fields throughout the file.`, so the behavior of FireDucks should be **correct**. And original Pandas is strange somehow.

But I think this kind of difference slightly breaks the compatibility between Pandas and FireDucks. When Pandas user turns to use FireDucks with their familiar datasets, it's a bad idea to give an error here scarring them away ;-) 

Tested on:

- FireDucks version: 0.10.1
- OS: Ubuntu 22.04.3 LTS (GNU/Linux 6.1.0-17-amd64 x86_64)
- Python3 version: Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux

**Comment by qsourav** [comment]
Hello @xxsl,

Thank you for reporting the issue.

As you rightly said such behaviors are not very likely in a properly formatted csv file, the internal library which we are using from reading csv files doesn't support such cases and raises parsing error with proper explanation.

In case such issues are taken care of by the internal library in future, it would be automatically working with FireDucks as well.
At this moment, there seems to be no concrete plan for addressing such issues.

We appreciate your kind consideration in this regard.

**Comment by xxsl** [comment]
Thanks for your explanations.
Since this is not intended to be fixed in short time, I shall close the issue.

**Comment by qsourav** [comment]
@xxsl ,

Hope you are doing well.
Although initially, we decided not to fix such issues, we realized having such a case is not very irregular, and aborting with an execution error for such a case might not be a good experience for the user.

**Comment by xxsl** [comment]
@qsourav 

Thanks for the updating, greate job!
I can also confirm it get fixed in latest version 0.11.4.

![2024-05-28_19-12](https://github.com/fireducks-dev/fireducks/assets/7067381/578eb728-0cf2-462c-bab3-d5550a613274)

Have a nice day!
